Repository Zandario/Citadel-Station-13-RP, pull requests merged in 2022-12, with the labels that each got.

#5 Workflows/updates
  .github/CODEOWNERS
  .github/workflows/auto_changelong.yml
  .github/workflows/ci_suite.yml
  .github/workflows/codeowner_reviews.yml
  .github/workflows/compile_changelogs.yml
  .github/workflows/conflicts.yml
  .github/workflows/generate_documentation.yml
  .github/workflows/round_id_linker.yml
  .github/workflows/size_labeling.yml
  .github/workflows/stale.yml
  tools/WebhookProcessor/github_webhook_processor.php
  tools/WebhookProcessor/secret.php
  tools/pull_request_hooks/autoChangelog.js
  tools/pull_request_hooks/autoChangelog.test.js
  tools/pull_request_hooks/changelogConfig.js
  tools/pull_request_hooks/changelogParser.js
  tools/pull_request_hooks/changelogParser.test.js
Labels: size/XL

#6 Workflows/updates
  .github/CODEOWNERS
  tools/pull_request_hooks/package.json
Labels: size/S

#10 Ambient Lights: Fix inconsistent corner init
  code/modules/lighting/lighting_turf.dm
Labels: size/S

#12 Z-Mimic Fixes Pack 1
  code/controllers/subsystem/air.dm
  code/controllers/subsystem/lighting.dm
  code/controllers/subsystem/machines.dm
  code/controllers/subsystem/openspace.dm
  code/controllers/subsystem/zmimic.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/multiz/zmimic/mimic_movable.dm
  code/modules/multiz/zmimic/mimic_turf.dm
Labels: size/L

#13 Z-Mimic Fixes Pack 2
  code/__DEFINES/rendering/zmimic.dm
  code/controllers/subsystem/zmimic.dm
  code/modules/lighting/lighting_turf.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/multiz/zmimic/_mimic_docs.dm
  code/modules/multiz/zmimic/mimic_movable.dm
  code/modules/power/lighting/lighting.dm
  code/modules/power/lighting/lights.dm
Labels: size/M
